#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: turkey-app-webserver
  namespace: turkey-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - image: gcr.io/pc-api-6479467557629758909-343/github_yes-soft-de_turkish-app
          imagePullPolicy: Always
          name: php-apache
          env:
           - name: MYSQL_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: turkey-app-mysql-secrets
                 key: userpassword
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/upload/image
              name: turkey-app-pvc-sym-m
      volumes:
        - name: turkey-app-pvc-sym-m
          persistentVolumeClaim:
            claimName: turkey-app-pvc-sym-uploud
