apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: turkey-app-webserver
  namespace: turkey-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: userpassword
                  name: turkey-app-mysql-secrets
          image: >-
            gcr.io/pc-api-6479467557629758909-343/github.com/yes-soft-de/turkish-app
          imagePullPolicy: Always
          name: php-apache
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/upload/image
              name: turkey-app-pvc-sym-m
      volumes:
        - name: turkey-app-pvc-sym-m
          persistentVolumeClaim:
            claimName: turkey-app-pvc-sym-uploud
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: apache
  name: turkey-app-webserver-service
  namespace: turkey-app
spec:
  clusterIP: 10.4.10.66
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: apache
  sessionAffinity: None
  type: ClusterIP
