App\Request\UploadImageRequest:
  properties:
    uploadedFile:
      - Image:
          #mimeTypesMessage: "this id not message"
          maxSize: 2m
          maxSizeMessage: "Image size over 2M"

<<<<<<< HEAD
App\Request\RealEstateCreateRequest:
  properties:
    city:
      - NotBlank: ~
    space:
      - NotBlank: ~
    price:
      - NotBlank: ~
    description:
=======
App\Request\CreateImageRequest:
  properties:
    image:
      - NotBlank: ~

App\Request\UpdateImageRequest:
  properties:
    image:
      - NotBlank: ~

App\Request\CarCreateRequest:
  properties:
    brand:
      - NotBlank: ~
    company:
      - NotBlank: ~
    engine:
      - NotBlank: ~
    price:
>>>>>>> 9ee4a3e03d164ef6c33b2bae96f4e7ce0b445c80
      - NotBlank: ~
    status:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~
<<<<<<< HEAD
    state:
      - NotBlank: ~

App\Request\RealEstateUpdateRequest:
  properties:
    city:
      - NotBlank: ~
    space:
      - NotBlank: ~
    price:
      - NotBlank: ~
    description:
=======
    distance:
      - NotBlank: ~
    carType:
      - NotBlank: ~
    fuel:
      - NotBlank: ~
    cc:
      - NotBlank: ~
    location:
      - NotBlank: ~
    gearType:
      - NotBlank: ~

App\Request\CarUpdateRequest:
  properties:
    brand:
      - NotBlank: ~
    company:
      - NotBlank: ~
    engine:
      - NotBlank: ~
    price:
>>>>>>> 9ee4a3e03d164ef6c33b2bae96f4e7ce0b445c80
      - NotBlank: ~
    status:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~
<<<<<<< HEAD
    state:
      - NotBlank: ~

App\Request\StatusCreateRequest:
  properties:
    userID:
      - NotBlank: ~
    LawyerID:
=======
    distance:
      - NotBlank: ~
    carType:
      - NotBlank: ~
    fuel:
      - NotBlank: ~
    cc:
      - NotBlank: ~
    location:
      - NotBlank: ~
    gearType:
      - NotBlank: ~

App\Request\DeviceCreateRequest:
  properties:
    brand:
      - NotBlank: ~
    cpu:
      - NotBlank: ~
    ram:
      - NotBlank: ~
    battery:
      - NotBlank: ~
    price:
>>>>>>> 9ee4a3e03d164ef6c33b2bae96f4e7ce0b445c80
      - NotBlank: ~
    status:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~
<<<<<<< HEAD

App\Request\StatusUpdateRequest:
  properties:
    userID:
      - NotBlank: ~
    LawyerID:
=======
    gauge:
      - NotBlank: ~
    durationOfUse:
      - NotBlank: ~
    location:
      - NotBlank: ~

App\Request\DeviceUpdateRequest:
  properties:
    brand:
      - NotBlank: ~
    cpu:
      - NotBlank: ~
    ram:
      - NotBlank: ~
    battery:
      - NotBlank: ~
    price:
>>>>>>> 9ee4a3e03d164ef6c33b2bae96f4e7ce0b445c80
      - NotBlank: ~
    status:
      - NotBlank: ~
    createdBy:
<<<<<<< HEAD
      - NotBlank: ~
=======
      - NotBlank: ~
    gauge:
      - NotBlank: ~
    durationOfUse:
      - NotBlank: ~
    location:
      - NotBlank: ~
>>>>>>> 9ee4a3e03d164ef6c33b2bae96f4e7ce0b445c80
