App\Request\UploadImageRequest:
  properties:
    uploadedFile:
      - Image:
          #mimeTypesMessage: "this id not message"
          maxSize: 2m
          maxSizeMessage: "Image size over 2M"

App\Request\CreateImageRequest:
  properties:
    image:
      - NotBlank: ~

App\Request\UpdateImageRequest:
  properties:
    image:
      - NotBlank: ~

App\Request\CarCreateRequest:
  properties:
    brand:
      - NotBlank: ~
    company:
      - NotBlank: ~
    engine:
      - NotBlank: ~
    price:
      - NotBlank: ~
    status:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~
    distance:
      - NotBlank: ~
    carType:
      - NotBlank: ~
    fuel:
      - NotBlank: ~
    cc:
      - NotBlank: ~
    location:
      - NotBlank: ~
    gearType:
      - NotBlank: ~

App\Request\CarUpdateRequest:
  properties:
    brand:
      - NotBlank: ~
    company:
      - NotBlank: ~
    engine:
      - NotBlank: ~
    price:
      - NotBlank: ~
    status:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~
    distance:
      - NotBlank: ~
    carType:
      - NotBlank: ~
    fuel:
      - NotBlank: ~
    cc:
      - NotBlank: ~
    location:
      - NotBlank: ~
    gearType:
      - NotBlank: ~

App\Request\DeviceCreateRequest:
  properties:
    brand:
      - NotBlank: ~
    cpu:
      - NotBlank: ~
    ram:
      - NotBlank: ~
    battery:
      - NotBlank: ~
    price:
      - NotBlank: ~
    status:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~
    gauge:
      - NotBlank: ~
    durationOfUse:
      - NotBlank: ~
    location:
      - NotBlank: ~

App\Request\DeviceUpdateRequest:
  properties:
    brand:
      - NotBlank: ~
    cpu:
      - NotBlank: ~
    ram:
      - NotBlank: ~
    battery:
      - NotBlank: ~
    price:
      - NotBlank: ~
    status:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~
    gauge:
      - NotBlank: ~
    durationOfUse:
      - NotBlank: ~
    location:
      - NotBlank: ~
